---
version: "2.1"
services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    networks:
      - pritunl
    ports:
      - "27017"
    volumes:
      - /opt/mongo/data:/data/db
    restart: always
  pritunl:
    container_name: pritunl
    build:
      context: .
      dockerfile: Dockerfile.amznlinux
    image: pritunl
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 64000
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "80:80"
      - "443:443"
      - "1194:1194/udp"
    restart: always
networks:
  pritunl:
